import React from 'react';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { FileEntry } from '../store';
import { Preview } from './Preview';

type PreviewStoreState = {
  previewExecutableScripts: boolean;
};

type PreviewFile = {
  name: string;
  path: string;
  type: string;
  url?: string;
  content?: string;
  externalTool?: string;
  archiveInfo?: {
    format: string;
    entry_count: number;
    total_size: number;
    compressed_size: number;
    entries: Array<{
      path: string;
      size: number;
      compressed_size: number;
      is_dir: boolean;
    }>;
  };
};

const mocks = vi.hoisted(() => ({
  storeState: {
    previewExecutableScripts: false,
  } as PreviewStoreState,
  areFinderTagsAvailable: vi.fn(),
}));

vi.mock('../store', () => ({
  useFileStore: (selector: (state: PreviewStoreState) => unknown) => selector(mocks.storeState),
}));

vi.mock('../services/finderIntegration', () => ({
  areFinderTagsAvailable: mocks.areFinderTagsAvailable,
}));

vi.mock('./FinderTags', () => ({
  FinderTags: ({ path }: { path: string }) => <div data-testid="finder-tags">{path}</div>,
}));

vi.mock('./CustomFieldsEditor', () => ({
  CustomFieldsEditor: ({
    file,
    onUpdate,
  }: {
    file: FileEntry;
    onUpdate?: (updatedFile: FileEntry) => void;
  }) => (
    <button
      type="button"
      onClick={() =>
        onUpdate?.({
          ...file,
          custom: {
            ...file.custom,
            status: 'done',
          },
        })
      }
    >
      Mock custom fields
    </button>
  ),
}));

function previewFile(overrides: Partial<PreviewFile> = {}): PreviewFile {
  return {
    name: 'readme.txt',
    path: '/workspace/readme.txt',
    type: 'text/plain',
    content: 'Hello world',
    ...overrides,
  };
}

function fileEntry(overrides: Partial<FileEntry> = {}): FileEntry {
  return {
    id: 'file-1',
    path: '/workspace/report.txt',
    name: 'report.txt',
    size: 2048,
    modified: '2026-01-15T12:00:00Z',
    hidden: false,
    is_dir: false,
    custom: {
      owner: 'Design',
    },
    ...overrides,
  };
}

describe('Preview', () => {
  beforeEach(() => {
    mocks.storeState.previewExecutableScripts = false;
    mocks.areFinderTagsAvailable.mockReset();
    mocks.areFinderTagsAvailable.mockResolvedValue(false);
  });

  afterEach(() => {
    cleanup();
  });

  it('renders image previews and wires close/ready/error callbacks', async () => {
    const user = userEvent.setup();
    const onClose = vi.fn();
    const onReady = vi.fn();
    const onContentError = vi.fn();

    render(
      <Preview
        file={previewFile({
          name: 'photo.png',
          path: '/workspace/photo.png',
          type: 'image/png',
          url: 'asset://photo.png',
        })}
        onClose={onClose}
        onReady={onReady}
        onContentError={onContentError}
      />
    );

    const image = screen.getByRole('img', { name: 'photo.png' });
    fireEvent.load(image);
    fireEvent.error(image);
    await user.click(screen.getByRole('button', { name: 'Close preview' }));

    expect(onReady).toHaveBeenCalledTimes(1);
    expect(onContentError).toHaveBeenCalledTimes(1);
    expect(onClose).toHaveBeenCalledTimes(1);
  });

  it('surfaces the external tool used for generated previews', () => {
    render(
      <Preview
        file={previewFile({
          name: 'clip.avi',
          path: '/workspace/clip.avi',
          type: 'video/avi',
          url: 'asset://preview/clip.mp4',
          externalTool: 'FFmpeg',
        })}
      />
    );

    expect(screen.getByText('Preview generated by FFmpeg')).toBeVisible();
  });

  it('shows loading and unsupported states when media has no preview URL', () => {
    const { rerender } = render(
      <Preview
        file={previewFile({
          path: '/workspace/photo.png',
          type: 'image/png',
          content: undefined,
        })}
        loading
      />
    );

    expect(screen.getByRole('status')).toHaveTextContent('Loading preview...');

    rerender(
      <Preview
        file={previewFile({
          path: '/workspace/photo.png',
          type: 'image/png',
          content: undefined,
        })}
      />
    );

    expect(screen.getByText('Cannot preview this image (no preview available).')).toBeVisible();
  });

  it('renders untrusted markdown as plain text', () => {
    const markdown =
      '# Title\n\n**bold** <script>alert(1)</script> [click](javascript:alert(2)) [x](" onmouseover="alert(3))';
    const { container } = render(
      <Preview
        file={previewFile({
          name: 'notes.md',
          path: '/workspace/notes.md',
          type: 'text/markdown',
          content: markdown,
        })}
      />
    );

    expect(container.querySelector('pre')?.textContent).toBe(markdown);
    expect(container.querySelector('script, a, [onmouseover]')).toBeNull();
  });

  it('renders code content without creating an HTML sink', () => {
    const source = '<img src=x onerror="alert(1)"><button onclick="alert(2)">run</button>';
    const { container } = render(
      <Preview
        file={previewFile({
          name: 'payload.ts',
          path: '/workspace/payload.ts',
          type: 'text/typescript',
          content: source,
        })}
      />
    );

    expect(container.querySelector('code')?.textContent).toBe(source);
    expect(container.querySelector('img, [onerror], [onclick]')).toBeNull();
  });

  it('respects the executable script preview setting', () => {
    const script = previewFile({
      name: 'setup.ps1',
      path: '/workspace/setup.ps1',
      type: 'text/plain',
      content: 'Write-Host "Installing"',
    });

    const { rerender, container } = render(<Preview file={script} />);

    expect(screen.getByText(/Script previews are disabled/)).toBeVisible();

    mocks.storeState.previewExecutableScripts = true;
    rerender(<Preview file={script} />);

    expect(container).toHaveTextContent('Write-Host');
    expect(screen.queryByText(/Script previews are disabled/)).not.toBeInTheDocument();
  });

  it('shows metadata, Finder tags, and custom field editor for file entries', async () => {
    const user = userEvent.setup();
    const onUpdate = vi.fn();
    mocks.areFinderTagsAvailable.mockResolvedValue(true);

    render(<Preview file={fileEntry()} onUpdate={onUpdate} />);

    await user.click(screen.getByRole('tab', { name: 'Metadata' }));

    expect(screen.getByText('Name:')).toBeVisible();
    expect(screen.getByText('report.txt')).toBeVisible();
    expect(screen.getByText('Path:')).toBeVisible();
    expect(screen.getAllByText('/workspace/report.txt').length).toBeGreaterThan(0);
    expect(screen.getByText('Size:')).toBeVisible();
    expect(screen.getByText('2 KB')).toBeVisible();

    await waitFor(() => expect(screen.getByText('Tags:')).toBeVisible());
    expect(screen.getByTestId('finder-tags')).toHaveTextContent('/workspace/report.txt');

    await user.click(screen.getByRole('tab', { name: 'Custom Fields' }));
    await user.click(screen.getByRole('button', { name: 'Mock custom fields' }));

    expect(onUpdate).toHaveBeenCalledWith(
      expect.objectContaining({
        custom: {
          owner: 'Design',
          status: 'done',
        },
      })
    );
  });

  it('renders archive previews with summary and entry list', () => {
    render(
      <Preview
        file={previewFile({
          name: 'bundle.zip',
          path: '/workspace/bundle.zip',
          type: 'application/x-explorie-archive',
          archiveInfo: {
            format: 'zip',
            entry_count: 2,
            total_size: 4096,
            compressed_size: 1024,
            entries: [
              { path: 'docs/readme.md', size: 512, compressed_size: 128, is_dir: false },
              { path: 'assets/', size: 0, compressed_size: 0, is_dir: true },
            ],
          },
        })}
      />
    );

    expect(screen.getByText('ZIP archive')).toBeVisible();
    expect(screen.getByText('2 entries')).toBeVisible();
    expect(screen.getByText('docs/readme.md')).toBeVisible();
    expect(screen.getByText('assets/')).toBeVisible();
  });

  it('renders Quick Look variant without side-panel tabs', () => {
    render(<Preview file={previewFile()} variant="quicklook" />);

    expect(screen.queryByRole('tablist', { name: 'Preview tabs' })).not.toBeInTheDocument();
    expect(screen.getByText('Hello world')).toBeVisible();
  });
});
