[workspace]
resolver = "3"
members = [
    "crates/core",
    "crates/native-services",
    "crates/ffmpeg-wrapper",
    "apps/cli",
    "apps/desktop/gpui"
]

[patch."https://github.com/zed-industries/zed"]
gpui_macos = { path = "vendor/gpui_macos" }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
