//! `DirectoryWindow` is split by feature area; each module adds an
//! `impl DirectoryWindow` block with the behavior for that area.

mod archives;
mod batch_rename_ui;
mod chrome;
mod commands;
pub(crate) use commands::OverlayUi;
mod context_menu;
pub(crate) use context_menu::ContextMenuUi;
mod custom_fields_ui;
mod diagnostics;
pub(crate) mod drag_drop;
mod entry_icons;
pub(crate) use entry_icons::EntryVisuals;
mod finder_tags;
mod layout;
pub(crate) use layout::WindowLayout;
mod lifecycle;
mod listing;
pub(crate) use listing::ColumnViewUi;
pub(crate) use listing::DiskInfoState;
pub(crate) use listing::ListingUi;
mod listing_view;
mod media;
mod mutation_prompts;
pub(crate) use mutation_prompts::MutationUi;
mod navigation;
pub(crate) use navigation::NavigationUi;
mod operations;
pub(crate) use operations::ClipboardUi;
pub(crate) use operations::OperationUi;
mod persistence;
mod preview;
pub(crate) use preview::PreviewUi;
pub(crate) use preview::QuickLookUi;
mod preview_view;
mod recovery;
pub(crate) use recovery::RecoveryUi;
mod remote_drives;
pub(crate) use remote_drives::RemoteDrivesUi;
mod render;
pub(crate) mod search;
pub(crate) use search::SearchUi;
mod selection;
mod settings_panel;
pub(crate) use settings_panel::SettingsUi;
mod smart_folders;
mod system;
pub(crate) use system::SystemUi;
mod text_input;
pub(crate) use text_input::NativeTextInputState;
mod text_preview;
mod toasts;
pub(crate) use toasts::ToastQueue;
mod watcher;
pub(crate) use watcher::WatcherUi;
mod workspaces;
pub(crate) use workspaces::WorkspaceUi;
